### ISSUE TITLE
How do i mod it

### ISSUE THREAD

**Issue by Alfacev3rd** [MobilePorting/FPS-Plus-Mobile#2]
This isnt really a issue but i would really like to mod fps plus, but if it bothers im sorry

**Comment by mcagabe19** [comment]
same as how do u do in Psych Engine the names are just different like it has `FPSPlus` on it

**Comment by Alfacev3rd** [comment]
the mods dont work because of the file of the characters, since fps plus characters file are .hxc the mods dont work

**Comment by mcagabe19** [comment]
not our issue
